version: "3.8"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - _ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - _ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - _ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data : {}

networks:
  default:
    name: mongodb_network
